-- MEDFLOW demo database
-- Run this file in Supabase SQL Editor.

create table if not exists public.emergency_requests (
  id bigint generated by default as identity primary key,
  resource text not null,
  quantity integer not null check (quantity > 0),
  department text not null,
  urgency text not null check (urgency in ('Critical', 'High', 'Normal')),
  status text not null default 'Open'
    check (status in ('Open', 'Matched')),
  created_at timestamptz not null default now()
);

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  type text not null default 'warning',
  title text not null,
  message text not null,
  time text not null default 'Just now',
  unread boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.emergency_requests
  (resource, quantity, department, urgency, status)
select 'ICU Beds', 2, 'Emergency', 'Critical', 'Open'
where not exists (
  select 1 from public.emergency_requests
);

insert into public.emergency_requests
  (resource, quantity, department, urgency, status)
select 'O+ Blood', 4, 'Blood Bank', 'High', 'Open'
where (
  select count(*) from public.emergency_requests
) = 1;

insert into public.alerts
  (type, title, message, time, unread)
select
  'critical',
  'ICU Capacity Critical',
  'ICU occupancy has reached 95%. Additional beds may be required.',
  '2 min ago',
  true
where not exists (
  select 1 from public.alerts
);

insert into public.alerts
  (type, title, message, time, unread)
select
  'warning',
  'O- Blood Supply Low',
  'Blood Bank inventory is below the recommended emergency level.',
  '8 min ago',
  true
where (
  select count(*) from public.alerts
) = 1;

alter table public.emergency_requests enable row level security;
alter table public.alerts enable row level security;

grant select, insert, update on public.emergency_requests to anon;
grant select, insert, update on public.alerts to anon;

drop policy if exists "Demo users can read emergency requests"
  on public.emergency_requests;
create policy "Demo users can read emergency requests"
  on public.emergency_requests
  for select
  to anon
  using (true);

drop policy if exists "Demo users can create emergency requests"
  on public.emergency_requests;
create policy "Demo users can create emergency requests"
  on public.emergency_requests
  for insert
  to anon
  with check (true);

drop policy if exists "Demo users can update emergency requests"
  on public.emergency_requests;
create policy "Demo users can update emergency requests"
  on public.emergency_requests
  for update
  to anon
  using (true)
  with check (true);

drop policy if exists "Demo users can read alerts"
  on public.alerts;
create policy "Demo users can read alerts"
  on public.alerts
  for select
  to anon
  using (true);

drop policy if exists "Demo users can create alerts"
  on public.alerts;
create policy "Demo users can create alerts"
  on public.alerts
  for insert
  to anon
  with check (true);

drop policy if exists "Demo users can update alerts"
  on public.alerts;
create policy "Demo users can update alerts"
  on public.alerts
  for update
  to anon
  using (true)
  with check (true);
