-- MEDFLOW demo database
-- Run this file in Supabase SQL Editor.

create table if not exists public.emergency_requests (
  id bigint generated by default as identity primary key,
  resource text not null,
  quantity integer not null check (quantity > 0),
  department text not null,
  urgency text not null check (urgency in ('Critical', 'High', 'Normal')),
  status text not null default 'Open'
    check (status in ('Open', 'Matched')),
  created_at timestamptz not null default now()
);

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  type text not null default 'warning',
  title text not null,
  message text not null,
  time text not null default 'Just now',
  unread boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.emergency_requests
  (resource, quantity, department, urgency, status)
select 'ICU Beds', 2, 'Emergency', 'Critical', 'Open'
where not exists (
  select 1 from public.emergency_requests
);

insert into public.emergency_requests
  (resource, quantity, department, urgency, status)
select 'O+ Blood', 4, 'Blood Bank', 'High', 'Open'
where (
  select count(*) from public.emergency_requests
) = 1;

insert into public.alerts
  (type, title, message, time, unread)
select
  'critical',
  'ICU Capacity Critical',
  'ICU occupancy has reached 95%. Additional beds may be required.',
  '2 min ago',
  true
where not exists (
  select 1 from public.alerts
);

insert into public.alerts
  (type, title, message, time, unread)
select
  'warning',
  'O- Blood Supply Low',
  'Blood Bank inventory is below the recommended emergency level.',
  '8 min ago',
  true
where (
  select count(*) from public.alerts
) = 1;

alter table public.emergency_requests enable row level security;
alter table public.alerts enable row level security;

grant select, insert, update on public.emergency_requests to anon;
grant select, insert, update on public.alerts to anon;

drop policy if exists "Demo users can read emergency requests"
  on public.emergency_requests;
create policy "Demo users can read emergency requests"
  on public.emergency_requests
  for select
  to anon
  using (true);

drop policy if exists "Demo users can create emergency requests"
  on public.emergency_requests;
create policy "Demo users can create emergency requests"
  on public.emergency_requests
  for insert
  to anon
  with check (true);

drop policy if exists "Demo users can update emergency requests"
  on public.emergency_requests;
create policy "Demo users can update emergency requests"
  on public.emergency_requests
  for update
  to anon
  using (true)
  with check (true);

drop policy if exists "Demo users can read alerts"
  on public.alerts;
create policy "Demo users can read alerts"
  on public.alerts
  for select
  to anon
  using (true);

drop policy if exists "Demo users can create alerts"
  on public.alerts;
create policy "Demo users can create alerts"
  on public.alerts
  for insert
  to anon
  with check (true);

drop policy if exists "Demo users can update alerts"
  on public.alerts;
create policy "Demo users can update alerts"
  on public.alerts
  for update
  to anon
  using (true)
  with check (true);


create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  short_code text not null,
  status text not null check (
    status in ('Critical', 'High', 'Moderate', 'Stable')
  ),
  capacity_total integer not null check (capacity_total > 0),
  capacity_occupied integer not null check (
    capacity_occupied >= 0
    and capacity_occupied <= capacity_total
  ),
  active_patients integer not null default 0 check (
    active_patients >= 0
  ),
  capacity_unit text not null default 'beds',
  created_at timestamptz not null default now()
);

insert into public.departments
  (name, short_code, status, capacity_total, capacity_occupied, active_patients, capacity_unit)
values
  ('Emergency', 'ER', 'Critical', 25, 23, 37, 'beds'),
  ('ICU', 'ICU', 'High', 20, 16, 16, 'beds'),
  ('General Ward', 'GW', 'Stable', 80, 34, 34, 'beds'),
  ('Surgery', 'SU', 'Moderate', 30, 18, 18, 'beds'),
  ('Radiology', 'RA', 'Stable', 12, 5, 9, 'rooms'),
  ('Pediatrics', 'PD', 'Stable', 24, 11, 11, 'beds')
on conflict (name) do update set
  short_code = excluded.short_code,
  status = excluded.status,
  capacity_total = excluded.capacity_total,
  capacity_occupied = excluded.capacity_occupied,
  active_patients = excluded.active_patients,
  capacity_unit = excluded.capacity_unit;

alter table public.departments enable row level security;

grant select on public.departments to anon;

drop policy if exists "Demo users can read departments"
  on public.departments;
create policy "Demo users can read departments"
  on public.departments
  for select
  to anon
  using (true);


create table if not exists public.hospital_resources (
  id bigint generated by default as identity primary key,
  resource_key text not null unique,
  label text not null,
  available integer not null default 0 check (available >= 0),
  in_use integer not null default 0 check (in_use >= 0),
  status text not null default 'Normal',
  detail text not null default '',
  created_at timestamptz not null default now()
);

insert into public.hospital_resources
  (resource_key, label, available, in_use, status, detail)
values
  ('available_beds', 'Available Beds', 42, 0, 'Normal', 'Across all departments'),
  ('icu_beds', 'ICU Beds', 8, 12, 'Normal', 'Currently available'),
  ('ventilators', 'Ventilators', 17, 5, 'Normal', '5 currently in use'),
  ('ambulances', 'Ambulances', 4, 0, 'Normal', 'Available for deployment'),
  ('blood_bank', 'Blood Bank', 0, 0, 'Low', 'Emergency inventory level')
on conflict (resource_key) do update set
  label = excluded.label,
  available = excluded.available,
  in_use = excluded.in_use,
  status = excluded.status,
  detail = excluded.detail;

alter table public.hospital_resources enable row level security;

grant select on public.hospital_resources to anon;

drop policy if exists "Demo users can read hospital resources"
  on public.hospital_resources;
create policy "Demo users can read hospital resources"
  on public.hospital_resources
  for select
  to anon
  using (true);
